# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NewReadSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'HandyJSON'
  pod 'AlamofireImage', '~> 3.1'
  # Pods for NewReadSwift
  pod 'Log'
end
